# Generated by Django 4.2.6 on 2024-04-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_alter_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
